enum STATES
{   
    ST_INIT,
    ST_CONNECTING,
    ST_CONNECTED,
    ST_NOT_CONNECTED,
    ST_LOW_WATER,
    ST_FULL_WATER,
    ST_PUMPING,
    ST_READY,
    ST_MANUAL_CONTROL,
    ST_WATER_FEED,
    ST_ERROR
};